import * as Phaser from 'phaser';

import type { SceneArtist } from '../art/contract';
import { sceneArtist } from '../art/SceneArtist';

/**
 * Single integration seam for the art lane: every scene in this lane gets its
 * SceneArtist from here, so a move or rename in the art module is a one-line
 * fix. The artist is stateless - all per-scene state lives in ArtContext.
 */
export function createArtist(): SceneArtist {
  return sceneArtist;
}

/**
 * BootScene - the only place raw textures are made.
 *
 * There are zero image files in this project, so every sprite the engine uses
 * (glows, sparkles, stars, confetti, soft fades) is painted into a canvas
 * texture here at boot and tinted per-scene afterwards.
 */

export const SCENE_KEYS = {
  boot: 'Boot',
  home: 'Home',
  story: 'Story',
  completion: 'Completion',
} as const;

/** Texture keys generated by BootScene. Tint these, never recolour by hand. */
export const TEX = {
  glow: 'fx-glow',
  dot: 'fx-dot',
  spark: 'fx-spark',
  star: 'fx-star',
  ring: 'fx-ring',
  fade: 'fx-fade',
  confetti: 'fx-confetti',
  pixel: 'fx-pixel',
} as const;

/** Typography. Web-safe stacks only - no font files exist to load. */
export const FONT = {
  /** Storybook narration: warm, bookish, high legibility at large sizes. */
  story: 'Georgia, "Iowan Old Style", "Palatino Linotype", "Times New Roman", serif',
  /** Big friendly UI: titles, buttons, Mimo's voice. */
  display: '"Trebuchet MS", "Segoe UI", Verdana, Tahoma, sans-serif',
} as const;

export function cssColor(hex: number): string {
  return `#${(hex >>> 0).toString(16).padStart(6, '0').slice(-6)}`;
}

export class BootScene extends Phaser.Scene {
  constructor() {
    super(SCENE_KEYS.boot);
  }

  create(): void {
    this.buildTextures();
    this.scene.start(SCENE_KEYS.home);
  }

  private buildTextures(): void {
    this.paint(TEX.glow, 128, 128, (ctx, w, h) => {
      const g = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, w / 2);
      g.addColorStop(0, 'rgba(255,255,255,1)');
      g.addColorStop(0.35, 'rgba(255,255,255,0.55)');
      g.addColorStop(0.72, 'rgba(255,255,255,0.16)');
      g.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, w, h);
    });

    this.paint(TEX.dot, 32, 32, (ctx, w, h) => {
      const g = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, w / 2);
      g.addColorStop(0, 'rgba(255,255,255,1)');
      g.addColorStop(0.62, 'rgba(255,255,255,0.92)');
      g.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, w, h);
    });

    this.paint(TEX.spark, 64, 64, (ctx, w, h) => {
      const cx = w / 2;
      const cy = h / 2;
      const glow = ctx.createRadialGradient(cx, cy, 0, cx, cy, cx);
      glow.addColorStop(0, 'rgba(255,255,255,0.9)');
      glow.addColorStop(0.4, 'rgba(255,255,255,0.18)');
      glow.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = glow;
      ctx.fillRect(0, 0, w, h);

      // Four-point sparkle: concave arms pinched at the centre.
      ctx.fillStyle = 'rgba(255,255,255,1)';
      ctx.beginPath();
      ctx.moveTo(cx, 1);
      ctx.quadraticCurveTo(cx + 5, cy - 5, w - 1, cy);
      ctx.quadraticCurveTo(cx + 5, cy + 5, cx, h - 1);
      ctx.quadraticCurveTo(cx - 5, cy + 5, 1, cy);
      ctx.quadraticCurveTo(cx - 5, cy - 5, cx, 1);
      ctx.fill();
    });

    this.paint(TEX.star, 72, 72, (ctx, w, h) => {
      ctx.fillStyle = 'rgba(255,255,255,1)';
      ctx.beginPath();
      starPath(ctx, w / 2, h / 2 + 2, 5, w / 2 - 3, (w / 2 - 3) * 0.46);
      ctx.fill();
    });

    this.paint(TEX.ring, 128, 128, (ctx, w, h) => {
      const cx = w / 2;
      const cy = h / 2;
      const glow = ctx.createRadialGradient(cx, cy, w * 0.3, cx, cy, cx);
      glow.addColorStop(0, 'rgba(255,255,255,0)');
      glow.addColorStop(0.72, 'rgba(255,255,255,0.35)');
      glow.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = glow;
      ctx.fillRect(0, 0, w, h);

      ctx.strokeStyle = 'rgba(255,255,255,1)';
      ctx.lineWidth = 6;
      ctx.beginPath();
      ctx.arc(cx, cy, cx - 8, 0, Math.PI * 2);
      ctx.stroke();
    });

    this.paint(TEX.fade, 8, 256, (ctx, w, h) => {
      const g = ctx.createLinearGradient(0, 0, 0, h);
      g.addColorStop(0, 'rgba(255,255,255,1)');
      g.addColorStop(0.55, 'rgba(255,255,255,0.45)');
      g.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, w, h);
    });

    this.paint(TEX.confetti, 16, 26, (ctx, w, h) => {
      ctx.fillStyle = 'rgba(255,255,255,1)';
      roundRect(ctx, 1, 1, w - 2, h - 2, 5);
      ctx.fill();
    });

    this.paint(TEX.pixel, 4, 4, (ctx, w, h) => {
      ctx.fillStyle = 'rgba(255,255,255,1)';
      ctx.fillRect(0, 0, w, h);
    });
  }

  private paint(
    key: string,
    width: number,
    height: number,
    draw: (ctx: CanvasRenderingContext2D, w: number, h: number) => void,
  ): void {
    if (this.textures.exists(key)) return;
    const texture = this.textures.createCanvas(key, width, height);
    if (!texture) return;
    const ctx = texture.getContext();
    ctx.clearRect(0, 0, width, height);
    draw(ctx, width, height);
    texture.refresh();
  }
}

/* ------------------------------------------------------------------ */
/* Shared UI primitives. Used by every scene in this lane.             */
/* ------------------------------------------------------------------ */

export interface WordSpec {
  text: string;
  style: Phaser.Types.GameObjects.Text.TextStyle;
  /** Marks a word the story asked to emphasise. */
  emphasis?: boolean;
}

export interface LaidOutWord {
  text: Phaser.GameObjects.Text;
  x: number;
  y: number;
  emphasis: boolean;
}

/**
 * Measure-then-place word layout. Needed because each word is its own Text
 * object (so narration can emphasise individual words and reveal them one at
 * a time), which rules out Phaser's built-in word wrap.
 *
 * Coordinates come back centred on (0,0) so the caller can drop them straight
 * into a container.
 */
export function layoutWords(
  scene: Phaser.Scene,
  words: WordSpec[],
  opts: { maxWidth: number; lineSpacing: number },
): { words: LaidOutWord[]; width: number; height: number } {
  const made = words.map((w) => {
    const text = scene.add.text(0, 0, w.text, w.style).setOrigin(0.5, 0.5);
    return { text, emphasis: w.emphasis === true };
  });

  const spaceWidth = made.reduce((max, m) => Math.max(max, m.text.height), 0) * 0.24;
  const lines: { items: typeof made; width: number }[] = [];
  let current: typeof made = [];
  let currentWidth = 0;

  for (const item of made) {
    const advance = current.length === 0 ? item.text.width : spaceWidth + item.text.width;
    if (current.length > 0 && currentWidth + advance > opts.maxWidth) {
      lines.push({ items: current, width: currentWidth });
      current = [item];
      currentWidth = item.text.width;
    } else {
      current.push(item);
      currentWidth += advance;
    }
  }
  if (current.length > 0) lines.push({ items: current, width: currentWidth });

  const height = Math.max(1, lines.length) * opts.lineSpacing;
  const width = lines.reduce((max, l) => Math.max(max, l.width), 0);
  const out: LaidOutWord[] = [];

  lines.forEach((line, lineIndex) => {
    let cursor = -line.width / 2;
    const y = -height / 2 + opts.lineSpacing * (lineIndex + 0.5);
    for (const item of line.items) {
      const x = cursor + item.text.width / 2;
      out.push({ text: item.text, x, y, emphasis: item.emphasis });
      cursor += item.text.width + spaceWidth;
    }
  });

  return { words: out, width, height };
}

export interface BigButtonOptions {
  label: string;
  x: number;
  y: number;
  width?: number;
  height?: number;
  fill: number;
  ink: number;
  fontSize?: number;
  onPress: () => void;
  onHover?: (over: boolean) => void;
}

/**
 * The only navigation a 5-year-old should ever need: one enormous, springy,
 * unmissable button.
 */
export function createBigButton(
  scene: Phaser.Scene,
  opts: BigButtonOptions,
): Phaser.GameObjects.Container {
  const w = opts.width ?? 340;
  const h = opts.height ?? 116;
  const radius = h / 2;
  const container = scene.add.container(opts.x, opts.y);

  const glow = scene.add.image(0, 6, TEX.glow).setDisplaySize(w * 1.6, h * 2.1);
  glow.setTint(opts.fill).setAlpha(0.4);

  const shadow = scene.add.graphics();
  shadow.fillStyle(0x000000, 0.22);
  shadow.fillRoundedRect(-w / 2, -h / 2 + 10, w, h, radius);

  const face = scene.add.graphics();
  face.fillStyle(opts.fill, 1);
  face.fillRoundedRect(-w / 2, -h / 2, w, h, radius);
  face.fillStyle(0xffffff, 0.18);
  face.fillRoundedRect(-w / 2 + 8, -h / 2 + 7, w - 16, h * 0.42, radius * 0.7);

  const label = scene.add
    .text(0, 0, opts.label, {
      fontFamily: FONT.display,
      fontSize: `${opts.fontSize ?? 46}px`,
      color: cssColor(opts.ink),
      fontStyle: 'bold',
    })
    .setOrigin(0.5)
    .setLetterSpacing(2);

  container.add([glow, shadow, face, label]);
  container.setSize(w, h);
  container.setInteractive({ useHandCursor: true });

  scene.tweens.add({
    targets: container,
    scale: 1.035,
    duration: 1400,
    yoyo: true,
    repeat: -1,
    ease: 'Sine.easeInOut',
  });
  scene.tweens.add({
    targets: glow,
    alpha: 0.68,
    duration: 1100,
    yoyo: true,
    repeat: -1,
    ease: 'Sine.easeInOut',
  });

  let pressed = false;
  container.on('pointerover', () => {
    label.setScale(1.06);
    opts.onHover?.(true);
  });
  container.on('pointerout', () => {
    label.setScale(1);
    opts.onHover?.(false);
  });
  container.on('pointerdown', () => {
    label.setScale(0.94);
  });
  container.on('pointerup', () => {
    if (pressed) return;
    pressed = true;
    container.disableInteractive();
    scene.tweens.killTweensOf(container);
    scene.tweens.add({
      targets: container,
      scale: 0.9,
      duration: 90,
      yoyo: true,
      ease: 'Quad.easeOut',
      onComplete: () => opts.onPress(),
    });
  });

  return container;
}

function starPath(
  ctx: CanvasRenderingContext2D,
  cx: number,
  cy: number,
  points: number,
  outer: number,
  inner: number,
): void {
  const step = Math.PI / points;
  let angle = -Math.PI / 2;
  ctx.moveTo(cx + Math.cos(angle) * outer, cy + Math.sin(angle) * outer);
  for (let i = 0; i < points; i += 1) {
    angle += step;
    ctx.lineTo(cx + Math.cos(angle) * inner, cy + Math.sin(angle) * inner);
    angle += step;
    ctx.lineTo(cx + Math.cos(angle) * outer, cy + Math.sin(angle) * outer);
  }
  ctx.closePath();
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
): void {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}
